name: 23
timestamp: 1529395549
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1529395549
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  messages:
    system-messages-6481: 'System Messages'
  logo:
    logo-5015: 'Logo / Image'
    logo-7002: 'Logo / Image'
  menu:
    menu-7157: Menu
  social:
    social-9253: Social
  copyright:
    copyright-6209: Copyright
  horizontalmenu:
    horizontalmenu-7389: 'Horizontal Menu'
  totop:
    totop-1333: 'To Top'
  mobile-menu:
    mobile-menu-8280: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-6481: system-messages-7972
    logo-5015: logo-9608
    menu-7157: menu-6409
    social-9253: social-3171
    logo-7002: logo-9571
    copyright-6209: copyright-1736
    horizontalmenu-7389: horizontalmenu-9034
    totop-1333: totop-8670
    mobile-menu-8280: mobile-menu-5697
